version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/server
    
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: /home/ec2-user/server/server_clean.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
     - location: /home/ec2-user/server/change_permissions.sh
       timeout: 300
       runas: ec2-user
  ApplicationStart:
     - location: /home/ec2-user/server/server_start.sh
       timeout: 300
       runas: ec2-user
  ValidateService:
     - location: /home/ec2-user/server/server_stop.sh
       timeout: 300
       ruas: ec2-user
  
    
